export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const SET_NOTES = 'SET_NOTES'
